-- MySQL Script generated by MySQL Workbench
-- Mon Sep 17 21:54:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scoretracker
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scoretracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scoretracker` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `scoretracker` ;

-- -----------------------------------------------------
-- Table `scoretracker`.`party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoretracker`.`party` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `party_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scoretracker`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoretracker`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC),
  UNIQUE INDEX `idrole_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scoretracker`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoretracker`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NOT NULL,
  `password` VARCHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_polish_ci' NULL,
  `email` VARCHAR(45) NULL,
  `role_id` INT UNSIGNED NOT NULL,
  `party_id` INT NULL,
  `registration_date` DATE NULL,
  `last_login` DATETIME NULL,
  `party_member_since` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_user_party1_idx` (`party_id` ASC),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_party1`
    FOREIGN KEY (`party_id`)
    REFERENCES `scoretracker`.`party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `scoretracker`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scoretracker`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoretracker`.`session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `browser` VARCHAR(25) NULL,
  `ip` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scoretracker`.`season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoretracker`.`season` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `party_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_season_party1_idx` (`party_id` ASC),
  CONSTRAINT `fk_season_party1`
    FOREIGN KEY (`party_id`)
    REFERENCES `scoretracker`.`party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scoretracker`.`tracker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoretracker`.`tracker` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `wins` INT UNSIGNED NULL,
  `amount` INT UNSIGNED NULL,
  `season_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tracker_season1_idx` (`season_id` ASC),
  INDEX `fk_tracker_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tracker_season1`
    FOREIGN KEY (`season_id`)
    REFERENCES `scoretracker`.`season` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tracker_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `scoretracker`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
